/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Original PanganLink Earthy Colors from HTML template
        "outline": "#81756d",
        "inverse-primary": "#e3c0a8",
        "surface-container": "#ffeade",
        "on-tertiary-container": "#a4bdc2",
        "on-primary-fixed": "#2a1708",
        "secondary-container": "#e7e1db",
        "primary-fixed-dim": "#e3c0a8",
        "tertiary-fixed": "#cee7ec",
        "primary-muted": "rgba(93, 68, 50, 0.1)",
        "error": "#ba1a1a",
        "on-secondary-container": "#67645f",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#061f22",
        "on-secondary-fixed": "#1d1b18",
        "success": "#16A34A",
        "surface-container-high": "#ffe3d2",
        "secondary-fixed": "#e7e1db",
        "error-container": "#ffdad6",
        "inverse-surface": "#3f2c1f",
        "secondary": "#615e59",
        "on-secondary-fixed-variant": "#494642",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#4f453e",
        "on-primary-fixed-variant": "#5a4230",
        "surface-bright": "#fff8f5",
        "primary-fixed": "#ffdcc5",
        "primary-container": "#5d4432",
        "surface-container-low": "#fff1ea",
        "on-primary": "#ffffff",
        "surface-dim": "#f4d4c0",
        "background": "#fff8f5",
        "danger": "#DC2626",
        "on-secondary": "#ffffff",
        "surface-tint": "#745946",
        "outline-variant": "#d3c4bb",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#b2cbd0",
        "inverse-on-surface": "#ffede4",
        "surface-variant": "#fddcc9",
        "on-background": "#28180c",
        "tertiary-container": "#364d51",
        "on-surface": "#28180c",
        "tertiary": "#1f363a",
        "surface": "#F9F7F5",
        "on-primary-container": "#d4b29b",
        "on-tertiary-fixed-variant": "#344a4e",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#cbc6c0",
        "surface-container-highest": "#fddcc9",
        "warning": "#D97706",
        "primary": "#442e1d",

        // Specific Brand Green Accent (Requested for Sidebar)
        "brand-green":       "#2D6A4F",
        "brand-green-light": "#52B788",
        "brand-green-pale":  "#D8F3DC",
        "brand-green-muted": "rgba(45, 106, 79, 0.08)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "sidebar-width": "256px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "gutter": "24px",
        "container-margin": "32px",
      },
      fontFamily: {
        sans:  ["'Be Vietnam Pro'", "sans-serif"],
        mono:  ["'JetBrains Mono'", "monospace"],
        "title-md":   ["'Be Vietnam Pro'", "sans-serif"],
        "headline-lg":["'Be Vietnam Pro'", "sans-serif"],
        "display-lg": ["'Be Vietnam Pro'", "sans-serif"],
        "data-lg":    ["'JetBrains Mono'", "monospace"],
        "label-sm":   ["'JetBrains Mono'", "monospace"],
        "body-md":    ["'Be Vietnam Pro'", "sans-serif"],
        "body-sm":    ["'Be Vietnam Pro'", "sans-serif"],
        "label-md":   ["'JetBrains Mono'", "monospace"],
      },
      fontSize: {
        "title-md":  ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-lg":  ["18px", { lineHeight: "1", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md":  ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm":  ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      boxShadow: {
        soft:  "0px 4px 20px rgba(62, 43, 30, 0.08)",
        card:  "0px 2px 12px rgba(62, 43, 30, 0.06)",
        popup: "0px 8px 32px rgba(62, 43, 30, 0.14)",
      },
      keyframes: {
        fadeUp: {
          "0%":   { opacity: "0", transform: "translateY(18px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%":   { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideInLeft: {
          "0%":   { opacity: "0", transform: "translateX(-16px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        shimmer: {
          "0%":   { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        pulse2: {
          "0%, 100%": { opacity: "1" },
          "50%":      { opacity: "0.5" },
        },
        scaleIn: {
          "0%":   { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
      },
      animation: {
        fadeUp:      "fadeUp 0.55s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        fadeIn:      "fadeIn 0.4s ease forwards",
        slideInLeft: "slideInLeft 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        shimmer:     "shimmer 2s linear infinite",
        pulse2:      "pulse2 2s ease-in-out infinite",
        scaleIn:     "scaleIn 0.35s cubic-bezier(0.16, 1, 0.3, 1) forwards",
      },
      transitionTimingFunction: {
        spring: "cubic-bezier(0.16, 1, 0.3, 1)",
      },
    },
  },
  plugins: [],
}
